name: Deploy

on:
  push:
    branches:
      - main # ⚠️ 네 브랜치 이름 맞게 수정 (master면 master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/chome49100/Discord-ChomiBot
            git pull origin main
            yarn install
            pm2 restart bot.js
